from .DataframeImageCategoricalPostprocessor import DataframeImageCategoricalPostprocessor
from .DataframeImageRepresentationPostprocessor import DataframeImageRepresentationPostprocessor

Registry = {
    'DataframeImageCategoricalPostprocessor': DataframeImageCategoricalPostprocessor,
    'DataframeImageRepresentationPostprocessor': DataframeImageRepresentationPostprocessor
}
